---
- name: Set Cilium Variables
  ansible.builtin.set_fact:
    kubernetes_core_workstations_cilium_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    kubernetes_core_workstations_cilium_version: "v0.16.24" # CLI Version
    kubernetes_core_workstations_cilium_cni_version: "1.16.0" # CNI Cluster Version

- name: Check if Cilium CLI is already installed
  ansible.builtin.command: "cilium version --client"
  register: kubernetes_core_workstations_cilium_cli_check
  changed_when: false
  failed_when: false
  become: true

- name: "Install Cilium CLI"
  when: >
    kubernetes_core_workstations_cilium_cli_check.rc != 0 or
    kubernetes_core_workstations_cilium_version not in kubernetes_core_workstations_cilium_cli_check.stdout
  block:
    - name: "Download Cilium CLI Checksum File"
      ansible.builtin.get_url:
        url: >-
          https://github.com/cilium/cilium-cli/releases/download/{{ kubernetes_core_workstations_cilium_version
          }}/cilium-linux-{{ kubernetes_core_workstations_cilium_arch }}.tar.gz.sha256sum
        dest: "/tmp/cilium.sha256"
        mode: "0644"
      become: true

    - name: "Read Checksum Content"
      ansible.builtin.slurp:
        src: "/tmp/cilium.sha256"
      register: kubernetes_core_workstations_cilium_checksum_file
      become: true

    - name: "Download Cilium CLI Binary"
      ansible.builtin.get_url:
        url: >-
          https://github.com/cilium/cilium-cli/releases/download/{{ kubernetes_core_workstations_cilium_version
          }}/cilium-linux-{{ kubernetes_core_workstations_cilium_arch }}.tar.gz
        dest: "/tmp/cilium-linux-{{ kubernetes_core_workstations_cilium_arch }}.tar.gz"
        mode: "0644"
        checksum: >-
          sha256:{{ kubernetes_core_workstations_cilium_checksum_file['content']
          | b64decode | split(' ') | first }}
      become: true

    - name: "Extract Cilium CLI Binary"
      ansible.builtin.unarchive:
        src: "/tmp/cilium-linux-{{ kubernetes_core_workstations_cilium_arch }}.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        mode: "0755"
      become: true

- name: "Install Cilium CNI Helm Installation"
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  ansible.builtin.shell:
    cmd: >
      cilium install --version {{ kubernetes_core_workstations_cilium_cni_version }} \
      --set cluster.name={{ node_name | lower | default('monster') }}-cluster \
      --set ipam.operator.clusterPoolIPv4PodCIDRList="{{ k8s_pod_cidr }}" \
      --set hubble.peerService.clusterDomain={{ cluster_domain }} \
      --set kubeProxyReplacement=true \
      --set k8sServiceHost={{ k8s_api_server_host }} \
      --set k8sServicePort={{ k8s_api_server_port }}
  become: true
  register: kubernetes_core_workstations_cilium_install_result
  changed_when: "'Cilium was successfully installed' in kubernetes_core_workstations_cilium_install_result.stdout"
  failed_when:
    - kubernetes_core_workstations_cilium_install_result.rc != 0
    - "'already installed' not in kubernetes_core_workstations_cilium_install_result.stderr"
    - "'cannot re-use a name' not in kubernetes_core_workstations_cilium_install_result.stderr"

- name: Trust Kubernetes Internal CIDRs (Pods and Services)
  ansible.posix.firewalld:
    zone: underlay_network
    rich_rule: 'rule family="ipv4" source address="{{ item }}" accept'
    state: enabled
    permanent: true
    immediate: true
  become: true
  loop:
    - "{{ k8s_pod_cidr }}"
    - "{{ k8s_service_cidr }}"
  notify:
    - Firewalld restart
  tags:
    - network_workstations

- name: Trust Cilium Virtual Interfaces
  # These interfaces handle intra-cluster traffic. In full eBPF mode,
  # packets must be allowed to flow through these without firewalld interception.
  ansible.posix.firewalld:
    zone: trusted
    interface: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  become: true
  loop:
    - cilium_host
    - cilium_net
    - cilium_vxlan
  notify:
    - Firewalld restart
  tags:
    - network_workstations

- name: 🛰️ Allow Hubble Relay & Agent communication
  ansible.posix.firewalld:
    zone: underlay_network
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  become: true
  loop:
    - 4244/tcp # Hubble Peer (Onde o Relay busca os dados)
    - 4245/tcp # Hubble Relay Server (Onde o UI/CLI conecta)
    - 4222/tcp # gRPC Health Check (O que está fazendo o Probe falhar!)
  tags:
    - network_workstations

- name: Flush Firewalld
  ansible.builtin.meta: flush_handlers

- name: "Enable Cilium Hubble & UI"
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  ansible.builtin.command:
    cmd: >
      cilium hubble enable --ui
  become: true
  register: kubernetes_core_workstations_cilium_hubble_result
  changed_when: "'Hubble was successfully enabled' in kubernetes_core_workstations_cilium_hubble_result.stdout"
  failed_when:
    - kubernetes_core_workstations_cilium_hubble_result.rc != 0
    - "'already enabled' not in kubernetes_core_workstations_cilium_hubble_result.stderr"
    - "'cannot re-use a name' not in kubernetes_core_workstations_cilium_hubble_result.stderr"
  notify: Restart Cilium Agents

- name: Flush Handlers to Apply Cilium Changes immediately
  ansible.builtin.meta: flush_handlers
