---

- name: Configure Bridge Nf Tables Calls and Ip Tables Forwarding for Kubernetes NLB Networking
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
  become: true

- name: Setup Network Services Permissions for Firewalld
  ansible.builtin.include_tasks:
    file: network-setup-services.yml

# - name: Map Internal Identity on /etc/hosts for Kubernetes Access using Internal Nodename
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     line: "{{ ansible_host }} {{ inventory_hostname }} {{ node_name | lower }}-workstation"
#     state: present
#     mode: '0644'
#     create: true
#   become: true
