---
- name: Gateway Certificate Generation Playbook
  hosts: Gateways
  become: true
  gather_facts: true
  tasks:
    - name: Generate Certificates for Services
      ansible.builtin.include_role:
        name: pki
      tags:
        - pki
        - certificates
