---
collections:
  - name: ansible.posix
    version: ">=2.1.0"

  - name: community.crypto
    version: ">=3.0.5"

  - name: community.general
    version: ">=12.1.0"

  - name: community.docker
    version: ">=5.0.4"
