---
- name: "Install External Secrets CRDs (server-side apply)"
  become: true
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/external-secrets/external-secrets/v0.12.1/deploy/crds/bundle.yaml"
    kubeconfig: /etc/kubernetes/admin.conf
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
