---
- name: "Install Traefik CRD"
  become: true
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/traefik/traefik/{{ traefik_version }}/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml"
    kubeconfig: /etc/kubernetes/admin.conf
