---
- name: Read Root CA Certificate
  ansible.builtin.slurp:
    src: /etc/kubernetes/pki/ca.crt
  register: kubernetes_cni_workstations_root_ca
  become: true

- name: Read K8s Ingress Certificate
  ansible.builtin.slurp:
    src: /etc/kubernetes/pki/kubernetes-ingress-traefik.crt
  register: kubernetes_cni_workstations_ingress_cert
  become: true

- name: Read K8s Ingress Certificate Key
  ansible.builtin.slurp:
    src: /etc/kubernetes/pki/kubernetes-ingress-traefik.key
  register: kubernetes_cni_workstations_ingress_cert_key
  become: true

- name: Build Shared Secrets Manifest (Reflector)
  ansible.builtin.template:
    src: shared_secrets.k8s.yml.j2
    dest: /tmp/shared_secrets.k8s.yml
    mode: '0644'
  become: true

- name: Apply Shared Secrets with Reflector Annotations
  become: true
  kubernetes.core.k8s:
    state: present
    src: /tmp/shared_secrets.k8s.yml
    kubeconfig: /etc/kubernetes/admin.conf
