---
# AdGuard DNS Settings
adguard_upstream_dns:
  - "1.1.1.1"
  - "8.8.8.8"
  - "https://dns.cloudflare.com/dns-query"
  - "https://dns.google/dns-query"

adguard_bootstrap_dns:
  - "1.1.1.1"
  - "8.8.8.8"

# AdGuard Performance Settings
adguard_ratelimit: 30
adguard_cache_size: 4194304
adguard_session_ttl: "720h"

# AdGuard Blocklists
adguard_filters:
  - enabled: true
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt"
    name: "AdGuard DNS filter"
  - enabled: true
    url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt"
    name: "AdAway Default Blocklist"

adguard_rewrites:
  - name: adguard
    dns: "dns.lab"
    description: DNS Authority
    ip: "{{ gateway_core_station_ip }}"

  - name: traefik
    dns: gateway.lab
    description: Gateway Proxy
    credential_certificate: true
    ip: "{{ gateway_core_station_ip }}"

  - name: upsnap-proxy
    dns: snap.lab
    description: Upsnap GhostTunnel Proxy Certificate
    ip: "{{ gateway_core_station_ip }}"

  - name: memos
    dns: daily.lab
    description: Memos Host, Fleeting Notes/Daily Journal
    ip: "{{ gateway_core_station_ip }}"

  - name: maybe-finance
    dns: finance.lab
    description: Maybe Finance GhostTunnel Proxy Certificate
    ip: "{{ gateway_core_station_ip }}"

  - name: trilium
    dns: brain.lab
    description: Trilium Host, Personal Knowledge Base
    ip: "{{ gateway_core_station_ip }}"

  - name: victoriametrics
    dns: "metrics.lab"
    description: VictoriaMetrics Metrics Database
    ip: "{{ gateway_core_station_ip }}"

  - name: grafana
    dns: "dash.lab"
    description: Grafana Dashboards
    ip: "{{ gateway_core_station_ip }}"

  - name: jaeger
    dns: "traces.lab"
    description: Jaeger Tracing Backend
    ip: "{{ gateway_core_station_ip }}"

  - name: jaeger-ingestion
    dns: "ingestion.traces.lab"
    description: Jaeger OTLP Ingestion Endpoint
    ip: "{{ gateway_core_station_ip }}"

  - name: K8s NLB Proxy
    dns: nlb.k8s.monster.lab
    description: Split-Horizon DNS - Kubernetes API Server via NLB
    ip: "{{ gateway_core_station_ip }}"

  - name: K8s Services Ingress
    dns: "*.svc.k8s.monster.lab"
    description: Split-Horizon DNS - Kubernetes Service FQDNs via Gateway Traefik
    ip: "{{ gateway_core_station_ip }}"

  - name: K8s Ingress Wildcard
    dns: "*.k8s.monster.lab"
    description: Split-Horizon DNS - Kubernetes Ingress Wildcard via Gateway Traefik
    ip: "{{ gateway_core_station_ip }}"

bastion_internal_hosts_dns:
  - name: Monster Workstation Machine
    dns: "k8s.monster.internal"
    description: Wildcard DNS for Monster Host Access via Traefik TCP Routing
    ip: "{{ workstation_core_station_ip }}"
