---
galaxy_info:
  author: gdavij
  description: "Optional Tailscale VPN (zero-trust network) installation and packet forwarding configuration"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [bookworm]
    - name: Fedora
      versions: [all]
dependencies: []
