---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: monster-workstation
  namespace: longhorn-system
spec:
  name: monster-workstation
  allowScheduling: true
  tags:
    - workstation
  disks:
    ssd:
      path: /k8s_storage
      allowScheduling: true
      storageReserved: 21474836480  # 20Gi reserved for system
      tags:
        - ssd
    hdd:
      path: /cold-storage/longhorn
      allowScheduling: true
      storageReserved: 10737418240  # 10Gi reserved for system
      tags:
        - hdd
