---
galaxy_info:
  author: gdavij
  description: "Traefik Ingress Controller and ArgoCD deployment for Kubernetes"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions: [all]
dependencies: []
