---
- name: Define Underlay Zone
  ansible.posix.firewalld:
    zone: underlay_network
    state: present
    permanent: true
    target: DROP
  become: true
  notify:
    - Reload Firewalld (Network Workstations)
  tags:
    - network_workstations

- name: Set Underlay Zone as Default zone on Workstation
  ansible.builtin.command:
    cmd: firewall-cmd --set-default-zone=underlay_network
  register: network_workstations_default_zone_check
  changed_when: "'already set' not in network_workstations_default_zone_check.stdout"
  become: true
  notify:
    - Reload Firewalld (Network Workstations)

- name: Flush Handlers to register Zone now
  ansible.builtin.meta: flush_handlers

- name: Bind Default Physical Network Interface into Underlay Zone(Security Group)
  ansible.posix.firewalld:
    zone: underlay_network
    interface: "{{ ansible_default_ipv4.interface }}"
    state: enabled
    permanent: true
    immediate: true
  become: true
  tags:
    - network_workstations

- name: 🛰️ Force Zone via NetworkManager (Fedora Fix)
  community.general.nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    zone: underlay_network
    state: present
    autoconnect: true
  become: true

- name: Enable Masquerading (NAT Gateway)
  ansible.posix.firewalld:
    zone: underlay_network
    masquerade: true
    state: enabled
    permanent: true
    immediate: true
  become: true
  tags:
    - network_workstations

- name: Define INGRESS Policies
  ansible.builtin.include_tasks:
    file: firewall-ingress-policies.yml
  tags:
    - network_workstations

- name: Define EGRESS Policies
  ansible.builtin.include_tasks:
    file: firewall-egress-policies.yml
  tags:
    - network_workstations
